### PR TITLE
Feature/smexoscope visual studio

### PR DESCRIPTION
**Pull request by dozius**
- Add some generated stuff to gitignore

- Explicitly include headers and vst/vstgui files so they show up in the
  project when working in VS (i.e. added clarity)

- Section off win32 and Mac stuff where appropriate

- Add def file and rc file

- Update def files

### CODE REVIEW

**Comment by bdejong** [comment]
Hi @dozius ,

thanks for these... I'm currently looking into a Contributor License Agreement... Even though these plugins are GPL, there are some people interested in licensing them. But they want a non-GPL license, so I have to make sure that contributors sign a license with me first. This is general practice for many open source projects:

https://en.wikipedia.org/wiki/Contributor_License_Agreement

 - bram

**Comment by bdejong** [comment]
https://github.com/bdejong/smartelectronix/wiki/CLA
contains the CLA... It was the standard form from harmonyagreements.org

**Comment by dozius** [comment]
Hi Bram,

I had a quick read through the CLA. The way it reads now I think my contributions could only be redistributed under the current license. It sounds like that is not what you want. From what I can tell in order to be able to re-license you need to choose a different outbound license option. 

From the guide:
- Option One: The original licenses
- Option Two: The original licenses and any additional licenses listed.
- Option Three: The original licenses and any additional licenses approved by the Open Source Initiative.
- Option Four: The original licenses and any additional licenses recommended by the Free Software Foundation.
- Option Five: Any license, with the promise back that the contribution will also be licensed under the original licenses.

-d

**Comment by bdejong** [comment]
Hey @dozius I'll read through it tonight and make sure everything is correct.

What I basically want to prevent is that when I license the code to a company under a secondary license I can still do that. I.e. the CLA enables me to sell a license which do not fall under GPL3.

**Comment by bdejong** [comment]
@dozius quickly checked and you are totally right. I will choose for option 5 and update the documents.

Thank you for reading through the documents so diligently!!

**Comment by dozius** [comment]
@bdejong You're welcome!

**Comment by bdejong** [comment]
@dozius I updated the CLA's. Meanwhile I've also pushed quite some changes to the repo which were still pending. If I had any idea there was anyone working on a pull request I would have been more diligent in pushing more frequently... Perhaps you could rebase your pull request?

**Comment by bdejong** [comment]
By the way, the full waveform display should be working again!!

**Comment by dozius** [comment]
Pulled in the new changes. Waveform is working here too! Seems like everything else is black though, could be a resource problem with the VS build. Will look into it when I get a chance.

I can still generate a VS 2015 project and build OK, so I think this PR is good to go. The issues above are outside the scope of this PR.

I will also review the updated CLA and if everything looks good will get a signed copy to you soon.

**Comment by bdejong** [comment]
:+1: As soon as I have the CLA I'll merge.

For the resources I changed all the resource names to strings rather than integer ID's so I'll have to follow this example for windows, I guess:

https://github.com/steinbergmedia/vstgui/blob/master/vstgui/tutorial/win/tutorial.rc

**Comment by bdejong** [comment]
Hey @dozius did you find some time to read/sign that CLA? It'd be real nice to merge this PR!

**Comment by dozius** [comment]
I printed out a copy this morning. Had to wait until I was back at work
since I don't have a printer at home.

Still trying to live the paperless dream. :)

I will try to get a signed copy emailed tonight!

**Comment by bdejong** [comment]
👍

**Pull request merged**
