### PR TITLE
Added windows resource file generation

### PR DESCRIPTION
**Pull request by bdejong**
@dozius Can you have a look at this one before I merge? If it works I'll also delete all resource files from the project...

### CODE REVIEW

**Comment by bdejong** [comment]
This should close #5 when done

**Comment by bdejong** [comment]
Already deleted resource files, otherwise this is quite useless :)

**Comment by dozius** [comment]
Had a quick look. Compiles OK. A couple of nitpicks.

* If I do an 'out of source' build the resource files are still generated inside the source tree. We could handle this by having git ignore resource files but I think it would be better to find a way to have the files generated in the build tree. 
* Currently you are hard coding to images/${FILENAME}. I think it would be better to use the full paths that are passed to the function. After all, those are the actual paths to the image files.

**Comment by dozius** [comment]
I looked into this a bit and did some quick tests that seem to check out.

For the 'out of source' generation you can use CMAKE_CURRENT_BINARY_DIR. This will be the same as CMAKE_CURRENT_SOURCE_DIR for in source builds and will be build tree for 'out of source' builds.

**Comment by bdejong** [comment]
Have a look again, @dozius

**Comment by dozius** [comment]
Looks good!

**Pull request merged**
