### PR TITLE
Port supaphaser

### PR DESCRIPTION
**Pull request by dozius**
Building and working in VstHost.

### CODE REVIEW

**Comment by bdejong** [comment]
Coooooool :)
Some of the comments say the GUI is not working, I suppose it actually is?

**Comment by dozius** [comment]
Yes, everything should be working now. Should have mentioned that in the last commit message. :grimacing:

**Comment by bdejong** [comment]
Merged!!

**Comment by bdejong** [comment]
FYI: I finally fixed this on macOS as well...

**Pull request merged**
