### PR TITLE
Fix x64 build

### PR DESCRIPTION
**Pull request by dozius**
- More correct CPU support look up

- Don't use unsupported MMX instructions

Might still be bugs but it loads up in Vsthost ok.

### CODE REVIEW

**Comment by bdejong** [comment]
Cool :-) I'll keep on working on the rest of the repo until I have everything building. But... This does prove that we can build multiple plugins inside the same repo. Now its just lather, rinse and repeat...

**Comment by bdejong** [comment]
PS: the artifact upload by two different CI's is proving to be a PITA. I'm in contact with both support teams to get it to work. Especially because when one works, the other tends to erase what the first created. #fail :-D

**Comment by dozius** [comment]
Cool, getting closer! I noticed you added each plugin port as an issue. If I start working on a port I will push a feature branch to my fork that tags the issue, just so we don't duplicate effort. Not going to have much time until the weekend this week though. You might be finished by then at this pace! :)

**Comment by bdejong** [comment]
Yeah, I added the H2O one as "finish implementation" so... you know which
one I'm working of for now. Easy ones should be supatrigger and crazyivanas
they don't have UI's...

Going through the code it does look like a lot of this stuff could use some
SERIOUS cleaning up. Organic code growth while learning C++ is scary. :-D

**Pull request merged**
