### PR TITLE
Feature/smexoscope win64 build

### PR DESCRIPTION
**Pull request by dozius**
Working builds for windows. Both x86 and x64 despite branch name.

### CODE REVIEW

**Comment by bdejong** [comment]
Hey Dozius, a few questions:

- I thought you had to include zlib and libpng in order to support PNGs. At least that is what the RTF in vstgui says.
- What version of windows are you testing on?
- OscilloscopeModular.def should really be moved to the root dir as "Smexoscope.def" and we should remove both the OscilloscopeModular and OscilloscopeNonModular directories. The Modular version is used very little I think and in any case, I removed the defines for it.
- It would be nice to also put the PROJECT_IMAGES in the visual studio project file.
- Smexoscope/images/readout2.png can probably be deleted. No idea why I had two :-)
- Any specific reason why you didn't want to include ${STEINBERG_DIR}/public.sdk/source/vst2.x but rather switched to using the full path in the cpp files?

**Comment by bdejong** [comment]
There is one error for OSX: `project(Smexoscope)` needs to be defined before you call find_library( ) in cmake, otherwise you get:

```
Missing variable is:
CMAKE_FIND_LIBRARY_PREFIXES
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
```

This is why I had put it at the top of the CMakeLists.txt, after the cmake version requirement...

You moved it down and copied it so there are two `project(Smexoscope)` calls in there. Other than that it compiles and runs with the PNG's!

**Comment by dozius** [comment]
1) I did too, but I can compile the example, this project and other vstgui
projects with pngs and it works. I am guessing the docs are out of date.

2) I am developing on Win 10, MSVC 2015. I have a win7 machine here I can
test on as well.

3) I agree, this was actually on my todo list.

4) I believe they automatically get included as part of the resources, so
explicitly including them in cmake is not required. I can double check when
I am at home.

5) Ha! Didn’t notice that. I will remove it, if you haven’t already.

6) Personal preference really. I find it more readable at a glance i.e. I
know where files are coming from. I also find it simpler to include
libraries/SDKs once. One include for VST SDK, one include for VSTGUI etc.

As for the cmake issue. I had read somewhere that CMAKE_OSX_ARCHITECTURES
needed to be set before the first project() which is why I kept it below.
Unfortunately I don’t have a mac to test on. Go ahead and make any changes
to the APPLE sections to get it working.

**Comment by bdejong** [comment]
Let's see who does what first 😄 

I also want to factor out the "generic" parts of this script into cmake functions so I can actually build ALL the projects while being DRY.

Don't bother testing on Win7... These are free plugins 😉

**Comment by dozius** [comment]
Sounds like a good plan. I've done similar things with qmake and a large modular library I developed for internal use at my company. Going to have to brush up on my Cmake. :sweat_smile:

**Comment by bdejong** [comment]
Hey @dozius I moved things around in the make file, to prepare for cutting the file into functions rather than repeating things in different subdirectories. Could you check if everything still builds on windows?

I will basically move VST Interface, VST GUI and General settings into functions rather than repeating them. Perhaps I can even do the same for all the rest of the code... No idea yet if I can pass a project name around, but I suppose I will be :)

Then the whole code should be reduced to something like:

```cmake
cmake_minimum_required(VERSION 3.5)

project(Smexoscope)

setup_vst()
setup_vstgui()

set(PROJECT_SOURCE
  SmartelectronixDisplayMain.cpp
  ...
)

set(PROJECT_IMAGES
  images/blue_knob1_4.png
  ...
)

build_vstgui_project(Smexoscope ${PROJECT_SOURCE} ${PROJECT_IMAGES})
```

an non-GUI projects would be

```cmake
cmake_minimum_required(VERSION 3.5)

project(Bleep)

setup_vst()

set(PROJECT_SOURCE
  Something.cpp
)

build_vst_project(Bleep ${PROJECT_SOURCE})
```

That's where I would like to get 😃

**Comment by bdejong** [comment]
Now that I think about it, `setup_vst()` and `setup_vstgui()` could be lumped into the `build_*` functions... Then it becomes VERY minimal...

**Pull request merged**
