### PR TITLE
Fix issue #28

### PR DESCRIPTION
**Pull request by dozius**
Don't use delete to free memory allocated with _aligned_malloc.

### CODE REVIEW

**Comment by bdejong** [comment]
Hi Dan,

Oh that's why it's crashing! I haven't really been looking for the fix,
just knew it was crashing @ exit.

I know this is a trivial change but could you please sign the CLA so I can
merge your change?

You can find it in the repo/wiki.

Bram

**Comment by dozius** [comment]
*ahem*

https://github.com/bdejong/smartelectronix/graphs/contributors

Has it been too long? 😄

**Comment by bdejong** [comment]
Oh dear. Didn't make the connection between username and real name.
Apologies.... Somehow the notification emails from GitHub now carry your
real name. Will merge!

**Comment by dozius** [comment]
:thumbsup:

**Pull request merged**
